### ISSUE TITLE
Groups not synced correctly when using project.yml

### ISSUE THREAD

**Issue by jurriaanr** [spicywebau/craft-neo#207]
#### Description
When grouping or ungrouping fields and than syncing the field on another server, the groups behave unpredictable.

F.e. The first time it works, but after that new fields are not added, the group is recreated when reordering fields inside, the group is duplicated with the old one now being empty. When removing the group altogether, the old copy and the new copy still exists, only the first field that was inside is now moved outside of the group on the server where it is synced, the rest still is inside the group, eventhough it doesnt exist at all any more on the originating installation. 

#### Steps to reproduce
1. Create a neo block with some fields
2. Create a group for (part of) those fields
3. Sync
4. Add new fields and sync. Good chance they are not added
5. Reorder fields inside group and sync. There are 2 groups now
6. Remove the group and sync. There are still 2 groups, only 1 field is moved outside

#### Other information
- Neo version: 2.3.0
- Craft version: 3.1.21
- Is the affected Craft installation multi-site: yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: yes

**Comment by proimage** [comment]
I'm seeing Group-related oddities as well. I had a Neo field (2.3.0.1) with blocks sorted into some groups, and after trying to add a new block, I went back and not only was the new block not there, neither were the groups.

**Comment by pvldigital** [comment]
Thanks @jurriaanr and @proimage. This should now be fixed in Neo 2.3.1.

**Comment by umkasanki** [comment]
I have the same issue
Neo 2.3.5
Craft Pro 3.1.34.2

Local:
![Screenshot_2019-07-24 ⚙ Create a new entry - Simplicate](https://user-images.githubusercontent.com/496132/61768453-2d94e600-adf0-11e9-8f50-968a6920f0c6.png)

Remote
![Screenshot_2019-07-24 🚧⚙ Create a new entry - Simplicate](https://user-images.githubusercontent.com/496132/61768553-79478f80-adf0-11e9-8d57-e52dacdb8a7b.png)

**Comment by httpster** [comment]
I'm still seeing this problem as well. I created multiple groups and a new block. When syncing the project.yaml I encountered an Internal Server Error and neither the groups nor the block were created.

Craft CMS: 3.3.17
Neo: 2.5.8
