### ISSUE TITLE
Error "Integrity constraint violation" when deleting a section

### ISSUE THREAD

**Issue by nitech** [spicywebau/craft-neo#239]
#### Description
When I try to delete a section that is available to one certain site, I get an "unknown error". Web.log says this: 

```log
2019-08-06 01:26:38 [-][1][-][info][yii\db\Command::execute] INSERT INTO `structures` (`maxLevels`, `uid`, `dateCreated`, `dateUpdated`) VALUES (NULL, '2d521888-6b2c-4c8b-b868-d1768ad020ad', '2019-08-06 08:26:38', '2019-08-06 08:26:38')
2019-08-06 01:26:38 [-][1][-][profile begin][yii\db\Command::execute] INSERT INTO `structures` (`maxLevels`, `uid`, `dateCreated`, `dateUpdated`) VALUES (NULL, '2d521888-6b2c-4c8b-b868-d1768ad020ad', '2019-08-06 08:26:38', '2019-08-06 08:26:38')
2019-08-06 01:26:38 [-][1][-][profile end][yii\db\Command::execute] INSERT INTO `structures` (`maxLevels`, `uid`, `dateCreated`, `dateUpdated`) VALUES (NULL, '2d521888-6b2c-4c8b-b868-d1768ad020ad', '2019-08-06 08:26:38', '2019-08-06 08:26:38')
2019-08-06 01:26:38 [-][1][-][info][yii\db\Command::execute] INSERT INTO `neoblockstructures` (`structureId`, `ownerId`, `ownerSiteId`, `fieldId`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1993, 7977, 0, 17, '2019-08-06 08:26:38', '2019-08-06 08:26:38', '400fa7d6-69f6-48f1-9a69-be69f057c967')
2019-08-06 01:26:38 [-][1][-][profile begin][yii\db\Command::execute] INSERT INTO `neoblockstructures` (`structureId`, `ownerId`, `ownerSiteId`, `fieldId`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1993, 7977, 0, 17, '2019-08-06 08:26:38', '2019-08-06 08:26:38', '400fa7d6-69f6-48f1-9a69-be69f057c967')
2019-08-06 01:26:38 [-][1][-][profile end][yii\db\Command::execute] INSERT INTO `neoblockstructures` (`structureId`, `ownerId`, `ownerSiteId`, `fieldId`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1993, 7977, 0, 17, '2019-08-06 08:26:38', '2019-08-06 08:26:38', '400fa7d6-69f6-48f1-9a69-be69f057c967')
2019-08-06 01:26:38 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back to savepoint 1
2019-08-06 01:26:38 [-][1][-][info][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-08-06 01:26:38 [-][1][-][profile begin][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-08-06 01:26:38 [-][1][-][profile end][yii\db\Command::execute] ROLLBACK TO SAVEPOINT LEVEL1
2019-08-06 01:26:38 [-][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2019-08-06 01:26:38 [-][1][-][error][yii\db\IntegrityException] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`client_dep_craft`.`neoblockstructures`, CONSTRAINT `neoblockstructures_ownerSiteId_fk` FOREIGN KEY (`ownerSiteId`) REFERENCES `sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) in C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Command.php:1290
Stack trace:
#0 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Command.php(1290): PDOStatement->execute()
#1 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `ne...')
#2 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Schema.php(433): yii\db\Command->execute()
#3 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\ActiveRecord.php(600): yii\db\Schema->insert('{{%neoblockstru...', Array)
#4 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 C:\client\client_dep_craft_hyperlane\vendor\spicyweb\craft-neo\src\services\Blocks.php(247): yii\db\BaseActiveRecord->save(false)
#7 C:\client\client_dep_craft_hyperlane\vendor\spicyweb\craft-neo\src\Field.php(746): benf\neo\services\Blocks->saveStructure(Object(benf\neo\models\BlockStructure))
#8 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\base\Element.php(2090): benf\neo\Field->beforeElementDelete(Object(craft\elements\Entry))
#9 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\elements\Entry.php(1229): craft\base\Element->beforeDelete()
#10 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Elements.php(1361): craft\elements\Entry->beforeDelete()
#11 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(1396): craft\services\Elements->deleteElement(Object(craft\elements\Entry))
#12 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(865): craft\services\Sections->handleDeletedEntryType(Object(craft\events\ConfigEvent))
#13 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#14 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#15 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(540): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#16 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(389): craft\services\ProjectConfig->processConfigChanges('sections.133e1d...', true)
#17 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(404): craft\services\ProjectConfig->set('sections.133e1d...', NULL)
#18 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(1354): craft\services\ProjectConfig->remove('sections.133e1d...')
#19 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(819): craft\services\Sections->deleteEntryType(Object(craft\models\EntryType))
#20 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(791): craft\services\Sections->deleteSection(Object(craft\models\Section))
#21 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\controllers\SectionsController.php(217): craft\services\Sections->deleteSectionById(22)
#22 [internal function]: craft\controllers\SectionsController->actionDeleteSection()
#23 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#24 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#25 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Controller.php(187): yii\base\Controller->runAction('delete-section', Array)
#26 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('delete-section', Array)
#27 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(299): yii\base\Module->runAction('sections/delete...', Array)
#28 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(566): craft\web\Application->runAction('sections/delete...', Array)
#29 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#30 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#31 C:\client\client_dep_craft_hyperlane\web\index.php(21): yii\base\Application->run()
#32 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`client_dep_craft`.`neoblockstructures`, CONSTRAINT `neoblockstructures_ownerSiteId_fk` FOREIGN KEY (`ownerSiteId`) REFERENCES `sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
The SQL being executed was: INSERT INTO `neoblockstructures` (`structureId`, `ownerId`, `ownerSiteId`, `fieldId`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1993, 7977, 0, 17, '2019-08-06 08:26:38', '2019-08-06 08:26:38', '400fa7d6-69f6-48f1-9a69-be69f057c967') in C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Schema.php:664
Stack trace:
#0 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `ne...')
#1 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Command.php(1091): yii\db\Command->internalExecute('INSERT INTO `ne...')
#2 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\Schema.php(433): yii\db\Command->execute()
#3 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\ActiveRecord.php(600): yii\db\Schema->insert('{{%neoblockstru...', Array)
#4 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\db\BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#6 C:\client\client_dep_craft_hyperlane\vendor\spicyweb\craft-neo\src\services\Blocks.php(247): yii\db\BaseActiveRecord->save(false)
#7 C:\client\client_dep_craft_hyperlane\vendor\spicyweb\craft-neo\src\Field.php(746): benf\neo\services\Blocks->saveStructure(Object(benf\neo\models\BlockStructure))
#8 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\base\Element.php(2090): benf\neo\Field->beforeElementDelete(Object(craft\elements\Entry))
#9 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\elements\Entry.php(1229): craft\base\Element->beforeDelete()
#10 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Elements.php(1361): craft\elements\Entry->beforeDelete()
#11 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(1396): craft\services\Elements->deleteElement(Object(craft\elements\Entry))
#12 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(865): craft\services\Sections->handleDeletedEntryType(Object(craft\events\ConfigEvent))
#13 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
#14 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
#15 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(540): yii\base\Component->trigger('removeItem', Object(craft\events\ConfigEvent))
#16 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(389): craft\services\ProjectConfig->processConfigChanges('sections.133e1d...', true)
#17 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\ProjectConfig.php(404): craft\services\ProjectConfig->set('sections.133e1d...', NULL)
#18 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(1354): craft\services\ProjectConfig->remove('sections.133e1d...')
#19 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(819): craft\services\Sections->deleteEntryType(Object(craft\models\EntryType))
#20 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\services\Sections.php(791): craft\services\Sections->deleteSection(Object(craft\models\Section))
#21 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\controllers\SectionsController.php(217): craft\services\Sections->deleteSectionById(22)
#22 [internal function]: craft\controllers\SectionsController->actionDeleteSection()
#23 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#24 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#25 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Controller.php(187): yii\base\Controller->runAction('delete-section', Array)
#26 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Module.php(528): craft\web\Controller->runAction('delete-section', Array)
#27 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(299): yii\base\Module->runAction('sections/delete...', Array)
#28 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(566): craft\web\Application->runAction('sections/delete...', Array)
#29 C:\client\client_dep_craft_hyperlane\vendor\craftcms\cms\src\web\Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#30 C:\client\client_dep_craft_hyperlane\vendor\yiisoft\yii2\base\Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#31 C:\client\client_dep_craft_hyperlane\web\index.php(21): yii\base\Application->run()
#32 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1452
    [2] => Cannot add or update a child row: a foreign key constraint fails (`client_dep_craft`.`neoblockstructures`, CONSTRAINT `neoblockstructures_ownerSiteId_fk` FOREIGN KEY (`ownerSiteId`) REFERENCES `sites` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
)
```

#### Other information
- Neo version: 2.4.0
- Craft version: 3.2.8
- Is the affected Craft installation multi-site: Yes
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: No

**Comment by pvldigital** [comment]
Hi @nitech,

From your logs I can see that it's trying to setup the neo structure with a `siteId` of `0` which throws an error because it couldn't find the `id` in the `sites` table. The `siteId` being `0` might be related to how neo was saving the blocks previously but I'm not too sure yet.

I'm trying to replicate this issue but currently unsuccessful in doing so. Can you give me more info on the sections setup? E.g. Type, Propagation method, is versioning enabled.

**Comment by nitech** [comment]
Is it easier for you if you get a copy of the database? Would you need the project also? Send me your email address at nitech (asasd) gmail.com and I'll send you what you need. 

Here is some additional info: 
Type: Single
Propagation Method -- not available on single
Versioning Enabled: Yes

When I look inside the database, I see that `neoblockstructures` has a lot of rows with `ownerSiteId == null`. Others again have one of the following `siteId`s: 

![image](https://user-images.githubusercontent.com/1279436/62600778-052ce180-b8f0-11e9-90ca-e9a828b8884f.png)

By the way, thanks for your prompt replies. I appreciate it.

**Comment by leigeber** [comment]
For what it's worth, getting a similar error when saving entries with Neo 2.4.0.

```
Foreign key violation: 7 ERROR:  insert or update on table "craft_neoblockstructures" violates foreign key constraint "craft_neoblockstructures_ownerSiteId_fk"
DETAIL:  Key (ownerSiteId)=(0) is not present in table "craft_sites".
```

The only valid site ID we have is 1.

**Comment by leigeber** [comment]
Seems to be resolved on my end by updating all NULL ownerSiteId values in craft_neoblockstructures to 1.

```sql
UPDATE craft_neoblockstructures
SET "ownerSiteId" = 1
WHERE "ownerSiteId" IS NULL
```

**Comment by theskyfloor** [comment]
@leigeber has this been good for you since you did that? considering updating

**Comment by leigeber** [comment]
@theskyfloor Yep, no error since then. Everything is saving as it should.

**Comment by pvldigital** [comment]
Hi @nitech @leigeber @theskyfloor ,

I've found the root of the issues and the fix will be released soon after testing.

The issue was because the blocks doesn't use `ownerSiteId` anymore in 3.2. When migrating from 3.1 -> 3.2 all entries was resaved and since we didn't release the changes in 2.4.0 yet the `ownerSiteId` in the `neoblockstructures` was saved as null.

The fix I'll add will be to check the structure for an `ownerSiteId`, if not found it'll get the id from the block and set it.

**Comment by pvldigital** [comment]
Hi All,

I've made a release for this issue. If there's still problems leave a comment and stack trace of it (found in the logs).

**Comment by nitech** [comment]
Hi @pvldigital, this solved the issue. Well done!

**Comment by BrandonJamesBorders** [comment]
@pvldigital I was getting the same sort of errors as @nitech, I updated and now I'm getting this error when trying to save an entry. Multi-site setup. Entry site ID is 2. 

Undefined offset: 2
1. in /mnt/c/sites/rev-group/vendor/spicyweb/craft-neo/src/Field.php

**Comment by pvldigital** [comment]
Hi @BrandonJamesBorders,

Release 2.4.2 should fix that issue. I needed to update the `$key` value if `ownerSiteId` was updated with the new id

**Comment by nitech** [comment]
I am afraid this still happens once in a while; when I edit an entry the text in the current entry gets propagated on all sites that share the entry, despite the propagation method being "language". 

In my setup I have two site groups with the following setup: 

- Site Group A
  - Site A - Norwegian
- Site Group B
  - Site B - Norwegian
  - Site C - English
  - Site D - Spanish

My experience is that when I edit the Norwegian site, sometimes that text gets propagated everywhere. 

I will add more info when it happens again. It's not consistent though - not as far as I can see. Could this be the same problem as being experienced here: https://github.com/spicywebau/craft-neo/issues/243 ?

**Comment by pvldigital** [comment]
@nitech the issue does sound similar to #243. if you have more info/logs, can you post it to that thread or create a new one.

**Comment by pvldigital** [comment]
@nitech this issue has been fixed with the latest release. it was not related to 243.

**Comment by nitech** [comment]
Thanks @pvldigital. I will update immediately and report back if I see it reoccurring. Awesome work!
