### ISSUE TITLE
Blocks being rendered multiple times on front-end 

### ISSUE THREAD

**Issue by louderthan10** [spicywebau/craft-neo#243]
#### Description
After updating to Neo 2.4.2, on some Structures, all the of the blocks are being repeated several times when rendered on the page (no extra blocks being created in the entry itself… those look fine).

#### Steps to reproduce
1. Have a multi-site Craft install with multiple sites
2. Create a Structure that's used in multiple sites
3. Upgrade Neo

I've also tried switching the Structure and Neo propagation methods to: `Save blocks to other sites in the same site group`, but it didn't do anything.

#### Other information
- Neo version: 2.4.2
- Craft version: 3.2.9
- Is the affected Craft installation multi-site: Y
- (if multi-site) Are the affected Neo fields set to manage blocks on a per-site basis: Yes, they were.

**Comment by nitech** [comment]
It sounds like it's related to this issue https://github.com/spicywebau/craft-neo/issues/242

Are the duplicated content visible inside the editor - or only on the front end? On my site, some of the duplicates on the front end are also visible in the editor, while others are only visible on the front end.

**Comment by louderthan10** [comment]
Yeah, I figured that the issues might be related, but wasn't sure because, as far as I can see at least, I'm only getting dupes on the front-end. I don't see any duplicate blocks in the entries in the editor. Also, this happened before switching the propagation method (though the field was set to manage blocks on a per-site basis pre-upgrade).

**Comment by nitech** [comment]
Ah, nice to see life signs from others with the same or similar problem. I've really been banging my head against the wall the last two days trying to find a solution - or at least a logic to when and why this is happening. 

On the positive side, I've started diving into the database structure of Craft CMS, and I like what I see.

**Comment by pvldigital** [comment]
Hi @louderthan10,

This issue should be fixed in Release v2.4.3.

**Comment by louderthan10** [comment]
@pvldigital Still getting the same issue over here after updating. Adding an example image:

Left is current live site (pre-upgrade) VS Right is local site (imported database from live, then upgraded Neo and Craft… this keeps repeat several times down the page)

![Live vs local + upgrade](https://user-images.githubusercontent.com/49751/63195788-6eb39b00-c028-11e9-8dbd-32bc8703f54d.png)

The editing screen of the entry itself looks fine.

**Comment by louderthan10** [comment]
Okay the really weird thing is that the entry Preview looks perfect while editing. It's just the published version on the front-end that gets messed up.

**Comment by pvldigital** [comment]
@louderthan10 Hmm that's strange. Can you try changing the neo field propagation method to another option and then back?

*Make sure neo field resaving queue job is completed after each option change.

**Comment by michaelhue** [comment]
@louderthan10 Do you use eager loading for the Neo field? I have similar problems with duplicated and unordered blocks, but only when using eager loading.

The template code could be useful to debug the issue.

**Comment by louderthan10** [comment]
@pvldigital Tried saving the field to "Only save blocks to the site they were created in", then waiting for the Neo fields to resave… same result on the front-end. Then switched back to "Save blocks to other sites in the same site group" and waited for the Neo blocks to resave… and same result.

---

@michaelhue Yes! I am using eager loading. Here's my Neo field template code (local version has template caching turned off right now):

```
{% cache globally using key craft.app.request.pathInfo ~ "-" ~ currentSite.handle ~ "-content" %}
{% minify %}
<section id="content">
  {% for block in entry.pageContent %}
    {% do block.useMemoized(entry.pageContent) %}
  {% endfor %}

  {% for block in entry.pageContent if block.level == 1 %}
    {% include ['_components/content/' ~ block.type, '_components/content/default'] %}
  {% endfor %}
</section>
{% endminify %}
{% endcache %}
```

Then each block type is in it's own component file.

**Comment by louderthan10** [comment]
Update: After looking closer at the Craft task list, I had a _huge_ list of failed tasks (including resaving Neo fields)… most were failed search engine indexing.

<img width="312" alt="Screen Shot 2019-08-19 at 11 26 01" src="https://user-images.githubusercontent.com/49751/63289824-e413ab80-c274-11e9-906d-74a95dacc455.png">

Then I went into the database and cleared out the craft queue table, then unchecked "Use this field’s values as search keywords?" and resaved the field. But looks like the Neo saving task is still failing:

<img width="406" alt="Screen Shot 2019-08-19 at 11 31 16" src="https://user-images.githubusercontent.com/49751/63289935-24732980-c275-11e9-8931-b81088d9c544.png">


Aside question: Do I need to check the "Use this field’s values as search keywords?" for Craft to index my Neo content, or does it automatically index the child fields?

**Comment by pvldigital** [comment]
Can you check the queue logs and send the stack trace of the issue? 

Nope, `use this fields values as search keywords` shouldn’t matter for content to be indexed

**Comment by louderthan10** [comment]
Alright, uploaded my log files in the attached zip. 

The web.log is isolated to one page load of that resources page. The queue log is so massive that one field save far exceeds 6 queue.log files so I tried to grab it right when the Neo saving task kicks in and first creates a log file (queu-start.log.1) and the log file right when the task fails (queue-end.log). 

Let me know if I can narrow this down somehow or get you something else. Not sure the best way to relay this info.

[lt10-neo-logs.zip](https://github.com/spicywebau/craft-neo/files/3517906/lt10-neo-logs.zip)

**Comment by pvldigital** [comment]
Thanks for that @louderthan10. I had a look and it seems like it's mainly for the search index queue job.

Within the queue logs, can you look for something like this: `[-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [####] Resaving neo blocks  (attempt: 1)`. It should provide you with the error after this.

*#### should be numbers.

**Comment by louderthan10** [comment]
@pvldigital Gotcha! Okay, So managed to copy a bunch of log files to see if I could catch the whole task. I just renamed them in order starting from the `Resaving neo blocks (attempt: 1)` line in `01queue.log`. Let me know if I didn't catch the whole thing.

[lt10.zip](https://github.com/spicywebau/craft-neo/files/3518446/lt10.zip)

**Comment by pvldigital** [comment]
@louderthan10 thanks again for the logs.

It seems like the resaving of the neo blocks is failing because of supertables.
Error:
`2019-08-19 19:09:51 [-][1][-][error][craft\queue\QueueLogBehavior::afterError]  [555375] Resaving neo blocks (attempt: 1) - Error (time: 64.243s): Invalid owner ID: 12924`

`2019-08-19 19:09:51 [-][1][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid owner ID: 12924 in ...../louderthanten/vendor/verbb/super-table/src/elements/SuperTableBlockElement.php:259`

The supertable block element is getting an invalid owner id.

**Comment by louderthan10** [comment]
@pvldigital Even if the Neo fields don't auto-resave, shouldn't the page go back to normal after manually resaving it?

**Comment by pvldigital** [comment]
@louderthan10 changing the neo field propagation resaves the fields so it's not the same as manually saving the entry.

I didn't see that you were using eager loading for the neo fields. The duplicate block on the front end was probably an issue with eager loading.

I've made a change on how eagerloading retrieves the blocks in my fork of neo: https://github.com/pvldigital/craft-neo

You can test it by cloning the repo, changing the require for neo to `"spicyweb/craft-neo": "^2.4.4",` and add the path to the clone repo. (on local or staging)
e.g:
```
{
   "type": "path",
   "url": "../../Plugins/craft-neo",
   "options": {
     "symlink": true
   }
},
```

**Comment by louderthan10** [comment]
@pvldigital That worked! Everything's loading correctly again.

**Comment by pvldigital** [comment]
@louderthan10 Awesome, good to know it's working. I'll make a release for it soon after some further testing and when I'm done fixing another issue.

**Comment by pvldigital** [comment]
@louderthan10 v2.4.4 is now released. this should fix the issues with the duplicating blocks.
