### ISSUE TITLE
Craft 3: Not receiving neo content from graphql with live-preview token

### ISSUE THREAD

**Issue by Jones-S** [spicywebau/craft-neo#273]
#### Description
I am setting up the preview part of my headless project and whenever I see a url param `'x-craft-live-preview'` I would load the content of my page via axios/graphql where I pass on the `token` and the `x-craft-live-preview` query to my graphql endpoint.
This gets me the latest draft of the entry I am requesting.
Not so for the neo field. I would just get an empty array (no blocks).

When I make the same request without the two tokens I would get the correct neo content (the last saved one), but whenever I want to get the draft with the tokens it is an empty array.

#### Steps to reproduce
1. Build a neo field with at least one block type
2. Write a query where the block type is requested
3. Request it normally from the graphql endpoint vs. request it by accesing the graphql endpoint with the two additional preview tokens from craft.
4. Normal request should return an array of neo blocks, a tokenized request returns an empty array.

#### Other information
- Neo version: 2.5.4
- Craft version: 3.4.x-dev
- Is the affected Craft installation multi-site: Nope
- Is eager-loading used? 🤷‍♂

**Comment by ca-miked** [comment]
I'm seeing this behaviour as well. Was just about to post a ticket but Jones-s beat me to it.

**Comment by pvldigital** [comment]
@ca-miked are you also using the `3.4.x-dev` branch?

**Comment by ca-miked** [comment]
No, I'm running version: 3.3.10

**Comment by pvldigital** [comment]
@ca-miked alright thanks

**Comment by pvldigital** [comment]
I have committed a fix for this issue. It can be tested by changing the composer file to `"spicyweb/craft-neo": "dev-master",` and using `composer update`. Will be making a release for it soon.

@Jones-S @ca-miked

**Comment by pvldigital** [comment]
release v2.5.5 should fix this issue.

**Comment by Jones-S** [comment]
It seems that this problem persists. I am getting all draft data via graphql but my neo field returns just an empty object... (I also made sure I had the newest version: `v. 2.7.18`...).

any idea what I am missing?
