### ISSUE TITLE
Multiple issues when updating from 3.4 to 3.5

### ISSUE THREAD

**Issue by jlcharette** [spicywebau/craft-neo#400]
#### Description
Multiple issues when upgrading from 3.4 to 3.5.

1. All fields are "required" in the blueprint configuration. Unchecking "required" and saving the field toggles the "required" back again. On the entry form, the fields don't appear as required even if they seem to be from the blueprint.

2. Migrating from 3.4 to 3.5 applies configuration changes to neo field (label, descriptions) when I run project-config/apply.
- Coworker still on 3.4
- Coworker checks out the updated branch with Craft/Plugins updates
- Coworker runs project-config/apply
- Git shows multiple configuration changes under craft/project/neoBlockTypes

I noticed the custom labels/notifications I have for some blocks are reset to null when I apply configurations. Also losing some UI-Element like Tips.

3. It is no longer possible to have empty tabs? I used to have a Content tab with child blocks and a settings tabs with fields on a "section block". Everytime I create my empty content tab, it gets removed on field save.

#### Other information
- Neo version: 2.8.7
- Craft version: 3.5.8
- (if multi-site) What is the affected Neo field's propagation method:
- Is eager-loading used? Yes

**Comment by ttempleton** [comment]
1. Issues with the display of required fields in Neo field layout designers with Craft 3.5.8 should be fixed in Neo 2.8.8.

2. Changes to Neo block types in the project config would not be unexpected after upgrading to Craft 3.5, with the changes to how field layouts work including labels/descriptions (and possibly also the new `maxSiblingBlocks` property that Neo 2.8 block types have).  Unless unnecessary changes are happening with every project config apply or field save?

Custom labels/descriptions and UI elements disappearing definitely shouldn't be happening, though.  I'll look into and see if I can reproduce that.

3. [As mentioned in the changelog for Neo 2.8.0](https://github.com/spicywebau/craft-neo/blob/master/CHANGELOG.md#280---2020-08-04), as part of the changes required for Neo to support Craft 3.5's new field layout designer, it's no longer possible for Neo to support blank tabs, and it's recommended to place a UI element in any blank tabs that should be kept.

**Comment by jwrudzin** [comment]
Relating to issue 1 - I'm running Craft 3.5.10.1 and Neo 2.8.8 now and I'm still seeing this. In the Neo field layout designer all fields are showing that they're required (they not only have a star next to the name, but when you click into the field settings the required lightswitch is toggled on. However, on the entry page, they are not actually required so this seems to be a bug only with the layout designer.

**Comment by ttempleton** [comment]
The incorrect display of non-required fields as required should now be fixed in Neo 2.8.9.

I was unable to reproduce the last part of issue 2 regarding labels and UI elements disappearing, though -- @jlcharette if possible could you please let me know the specific Craft/Neo versions you were upgrading from?

**Comment by ttempleton** [comment]
Closing this now; hopefully you've resolved part two of your issue, but if not, please let us know the information requested in my previous two comments and we'll reopen the issue.

**Comment by keenanpayne** [comment]
> It is no longer possible to have empty tabs? I used to have a Content tab with child blocks and a settings tabs with fields on a "section block". Everytime I create my empty content tab, it gets removed on field save.

In case anyone is looking for a workaround for the inability to have empty tabs 👇🏻

1. Create a tab that you want to be empty and place a `Template` UI Element inside of it
  - <img width="644" alt="Screen Shot 2020-11-18 at 5 37 27 PM" src="https://user-images.githubusercontent.com/1534650/99609495-dfccc580-29c4-11eb-99a5-b19b7969ebee.png">
2. Put the name of the template as `blank` and save your field
3. Navigate to the `templates` directory for your Craft CMS installation. Create a new file named `blank.twig` and save.

You will be able to save the empty tab without any content included. This will give you the appearance of having multiple tabs for your field.
<img width="728" alt="Screen Shot 2020-11-18 at 5 40 10 PM" src="https://user-images.githubusercontent.com/1534650/99609625-27ebe800-29c5-11eb-8327-c31a9dab8c72.png">
