### ISSUE TITLE
A (single) disabled NEO element disappears after entry save

### ISSUE THREAD

**Issue by craftedsystems** [spicywebau/craft-neo#627]
#### Description

Content gets lost, when saving entry with disabled NEO element(s). As long as there are other NEO elements that are not disabled, it seems to work. When all NEO elements are disabled, no matter how many, they disappear after saving the entry.

#### Steps to reproduce
1. Create NEO element
2. Disable it
3. Save entry
4. Entry is gone

#### Other information
- Neo version: 3.2.2 (same in 3.2.1; did not test with older versions)
- Craft version: 4.1.4.1
- (if multi-site) What is the affected Neo field's propagation method: Only save blocks to the site they were created in
- Is eager-loading used? no

**Comment by ttempleton** [comment]
Thanks for reporting this - turned out it happened when every block in the Neo field was disabled. I've just fixed that for the next release. In the meantime, you can get the fix by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.2.2` and running `composer update`.

**Comment by ttempleton** [comment]
Just released Neo 3.2.3 which includes the fix for this issue.

**Comment by rjgux** [comment]
@ttempleton I'm still experiencing this same issue, running Neo 3.2.5

**Comment by ttempleton** [comment]
@rjgux This was a different issue concerning cases where all blocks in the Neo field were disabled. If you're able to reliably reproduce this with Neo, and you're unable to reproduce it with Matrix, please open a new issue with detailed steps to reproduce.
