### ISSUE TITLE
Disappearing child blocks in UI element when updating visible elements

### ISSUE THREAD

**Issue by ttempleton** [spicywebau/craft-neo#777]
I'm unsure if this is related to the same issue, but we've also been experiencing disappearing neo-blocks. It usually occurs when a user changes the sort order of the blocks. I'd be happy to send over any project files if necessary.

Craft: 4.4.17
Neo: 3.8.6

https://github.com/spicywebau/craft-neo/assets/56364768/6d3d40a2-476c-4c6f-9ba9-0f3ed49b5b11

_Originally posted by @mjniland1 in https://github.com/spicywebau/craft-neo/issues/771#issuecomment-1684119330_

**Comment by aodihis** [comment]
I also face the content disappearing with this scenario:

1. Create an entry with Neo Field inside it.
2. Add an new block that may trigger a validation error. (For example a field that has required flag, but leave it empty).
3. Save entry before the applying draft finish. (So, the save will return an error, because of validation error of step 2).
4. Add another block. 

In step 4 the block we created in step 2 will disappear.


https://github.com/spicywebau/craft-neo/assets/18330728/69caeb47-840f-47c1-a518-ee40b7d22c8f

**Comment by ttempleton** [comment]
Thanks for reporting that @aodihis - just fixed that for the next release.

**Comment by Mathias-Syversen** [comment]
https://github.com/spicywebau/craft-neo/assets/53942798/c0d94256-62bb-455d-9d05-cff2c748a57d

I still have this issue on neo 3.9.0 and craft 4.5.5 when editing in live preview. It seems that the new field is reset to whatever it was when the live preview starts reloading the page. Anything changed or added while it loads is lost.

This is creating some issues when our users "quickly" edits a page, changing images, updating text etc. as it disappears if they are too quick.

I emptied all craft cache, including template cache, and forced a cache clear in the browser before recording this example.

**Comment by ttempleton** [comment]
Going to close this as a likely duplicate of #771

**Comment by ttempleton** [comment]
Reopening per https://github.com/spicywebau/craft-neo/issues/771#issuecomment-1730366450, maybe this isn't related... although that issue seems to have been fixed after running `php craft utils/fix-field-layout-uids` so try that and let me know if that resolves this issue.

**Comment by mjniland1** [comment]
My child blocks are now deleted entirely on save using Neo version 3.9.4. Reverting the page doesn't bring them back. This happens on local and productions even after running `php craft utils/fix-field-layout-uids`. Running the command now returns `Done. No duplicate UUIDs were found.`.

**Comment by ttempleton** [comment]
I've just pushed changes to the 3.x branch which should prevent updating of visible elements when creating new blocks, hopefully fixing this issue. If anyone following this issue would be willing to try it out and give feedback before I release it, you can try it by setting your composer.json file's `spicyweb/craft-neo` requirement to `3.x-dev as 3.9.4` and running `composer update`. I understand if you're not willing to try it before release, but any feedback is greatly appreciated, definitely want this one to be fixed for the next release.

@mjniland1 that video looks like probably a separate issue, but maybe worth trying out the above to see if that resolves it (though I suspect it won't). If it's started happening on 3.9+, setting the `enableLazyLoadingNewBlocks` plugin setting to `false` in the `config/neo.php` file should work around it for the time being.

**Comment by mjniland1** [comment]
I upgraded to 3.x-dev and set `enableLazyLoadingNewBlocks` to false but the problem persisted. I ended up narrowing it down to a conflict with a plugin called [User Activity](https://plugins.craftcms.com/activity?craft4). Removing this plugin fixed my issue for the time being. Thank you for the troubleshooting tips.
