### ISSUE TITLE
Invalid field layout ID: 319 (Changing a field in one layout block, changes the other)

### ISSUE THREAD

**Issue by JonnyBR12** [spicywebau/craft-neo#862]
### Bug Description

When visiting an entry that contains a Neo field, we're getting an internal server error which, when in dev mode, shows: 

Invalid field layout ID: 319
in /home/XXXXXX/public_html/_stage/vendor/spicyweb/craft-neo/src/assets/InputAsset.php at line 215– [yii\base\Component::__call](https://www.yiiframework.com/doc-2.0/yii-base-component.html#__call()-detail)('getFieldLayout', [])

When disabling Neo, the site works as expected. Can't think of anything that's updated or been changed since yesterday that could have caused this. Have you seen this before? Any help would be awesome.

### Steps to reproduce

1. Create an entry with a Neo field
2. Create new entry
3. Invalid field layout ID: 319 (or internal server error when live)

### Expected behaviour

We'd expect the Neo field to load successfully with all blocks editable as always.

### Neo version

4.0.6

### Craft CMS version

4.8.1

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by JonnyBR12** [comment]
Just to update on this, we've rolled the site back before this issue and it all comes down to two blocks created in Neo. 

To try and explain, we had a block 'Featured Cars' with a couple of text fields and a textarea in it. We cloned that and renamed it 'New Car Models'. When we then change a field in either, the field changed in the other block too. Deleting either of these results in internal server error. 

**To replicate:**

1. Create a block with a couple of fields in
2. Clone that block
3. Change a field in either and they both change
4. Deleting either of these fields now result in an internal server error with 'Invalid field layout ID'

**Comment by ttempleton** [comment]
Thanks for reporting this - I can't reproduce this error or the described behaviour, but I have just released 4.0.7 which fixes some other buggy behaviour affecting cloned block types which I'm hoping also fixes this. Could you please upgrade to 4.0.7 and let me know if that resolves your issue?

**Comment by JonnyBR12** [comment]
Thanks for getting back to me on this. I'm back in on Tuesday, so we'll upgrade to 4.0.7 and report back.

**Comment by mfell** [comment]
Hi, I just came across this issue. It’s still present and reproducible for me.  
Could you take a look at my ticket in the Craft repository (link above)? All the details are outlined there.

My most important question: How can I fix this without losing any data?

**Comment by ttempleton** [comment]
Thanks for that @mfell, will look into trying to reproduce that soon. In the meantime, could you please run `php craft neo/block-types/fix-field-layouts` and let me know if the issue persists.

**Comment by mfell** [comment]
Thanks @ttempleton ... i run php craft `neo/block-types/fix-field-layouts` but I still run into this PHP Error `Invalid field layout ID: 214`. Craft 4 and Neo are updated on their latest versions.

Let me know if I can do anything to support you ... this is really hard / impossible to solve for me.

**Comment by ttempleton** [comment]
That's now fixed in 4.2.19. You will need to run `php craft neo/block-types/fix-field-layouts` again after updating (possibly twice). Please let me know if the issue persists after that.

**Comment by mfell** [comment]
@ttempleton 

I updated Neo to 4.2.19 an run `php craft neo/block-types/fix-field-layouts` twice, but unfortunately, I’m still stuck with this ‘Invalid field layout ID’ error.

*reopen this issue*



```
xxx@xxx-web:/var/www/html$ php craft neo/block-types/fix-field-layouts
Exception 'yii\base\InvalidConfigException' with message 'Invalid field layout ID: 214'

in /var/www/html/vendor/craftcms/cms/src/behaviors/FieldLayoutBehavior.php:125

Stack trace:
#0 [internal function]: craft\behaviors\FieldLayoutBehavior->getFieldLayout()
#1 /var/www/html/vendor/yiisoft/yii2/base/Component.php(305): call_user_func_array(Array, Array)
#2 /var/www/html/vendor/spicyweb/craft-neo/src/console/controllers/BlockTypesController.php(346): yii\base\Component->__call('getFieldLayout', Array)
#3 [internal function]: benf\neo\console\controllers\BlockTypesController->actionFixFieldLayouts()
#4 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('fix-field-layou...', Array)
#7 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('fix-field-layou...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('fix-field-layou...', Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('fix-field-layou...', Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('neo/block-types...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('neo/block-types...', Array)
#12 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('neo/block-types...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#15 /var/www/html/craft(13): yii\base\Application->run()
#16 {main}
```

**Comment by ttempleton** [comment]
I'm guessing that the field layout was deleted along with a block type that was sharing it. I'm going to recommend taking a database backup, then finding the block type that has field layout ID 214 in the database, then finding the project config file for that block type (on Craft 4, file paths are in the format `config/project/neoBlockTypes/<handle>--<uid>.yaml`).

Then, either:

- if the field layout data is still in that file, run `php craft project-config/apply --force`
- if the field layout data is not in that file, find a version of the file in your Git history with the field layout data, copy it into the current version of the file, and run `php craft project-config/apply --force`

If that doesn't work, other options could be:

- check if the current database still has a row in the `fieldlayouts` table with ID 214 that has been soft-deleted
- check if a recent database backup has a row in the `fieldlayouts` table with ID 214, and importing that row, along with related rows in the `fieldlayouttabs` and `fieldlayoutfields` tables, into the current database.

**Comment by mfell** [comment]
Great, `php craft project-config/apply --force` worked perfectly, and the “Invalid field layout ID” issue is now resolved.

I also ran some tests with Neo, and it seems everything is functioning as expected. I think we can consider this issue closed now.

@ttempleton Thank you so much for your support!
